//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helpers.ServiceReference_Mail {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailParams", Namespace="http://schemas.datacontract.org/2004/07/PrestigeMailService.WebService")]
    [System.SerializableAttribute()]
    public partial class MailParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Helpers.ServiceReference_Mail.Attachement[] AttachementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailCcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ParametresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TemplateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helpers.ServiceReference_Mail.Attachement[] Attachements {
            get {
                return this.AttachementsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachementsField, value) != true)) {
                    this.AttachementsField = value;
                    this.RaisePropertyChanged("Attachements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailCc {
            get {
                return this.MailCcField;
            }
            set {
                if ((object.ReferenceEquals(this.MailCcField, value) != true)) {
                    this.MailCcField = value;
                    this.RaisePropertyChanged("MailCc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailTo {
            get {
                return this.MailToField;
            }
            set {
                if ((object.ReferenceEquals(this.MailToField, value) != true)) {
                    this.MailToField = value;
                    this.RaisePropertyChanged("MailTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Parametres {
            get {
                return this.ParametresField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametresField, value) != true)) {
                    this.ParametresField = value;
                    this.RaisePropertyChanged("Parametres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TemplateId {
            get {
                return this.TemplateIdField;
            }
            set {
                if ((this.TemplateIdField.Equals(value) != true)) {
                    this.TemplateIdField = value;
                    this.RaisePropertyChanged("TemplateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateName {
            get {
                return this.TemplateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateNameField, value) != true)) {
                    this.TemplateNameField = value;
                    this.RaisePropertyChanged("TemplateName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attachement", Namespace="http://schemas.datacontract.org/2004/07/MailService.Data.Models")]
    [System.SerializableAttribute()]
    public partial class Attachement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BinFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Helpers.ServiceReference_Mail.MailStack MailStackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BinFile {
            get {
                return this.BinFileField;
            }
            set {
                if ((object.ReferenceEquals(this.BinFileField, value) != true)) {
                    this.BinFileField = value;
                    this.RaisePropertyChanged("BinFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MailId {
            get {
                return this.MailIdField;
            }
            set {
                if ((this.MailIdField.Equals(value) != true)) {
                    this.MailIdField = value;
                    this.RaisePropertyChanged("MailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helpers.ServiceReference_Mail.MailStack MailStack {
            get {
                return this.MailStackField;
            }
            set {
                if ((object.ReferenceEquals(this.MailStackField, value) != true)) {
                    this.MailStackField = value;
                    this.RaisePropertyChanged("MailStack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailStack", Namespace="http://schemas.datacontract.org/2004/07/MailService.Data.Models")]
    [System.SerializableAttribute()]
    public partial class MailStack : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Helpers.ServiceReference_Mail.Attachement[] AttachementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SendDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helpers.ServiceReference_Mail.Attachement[] Attachements {
            get {
                return this.AttachementsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachementsField, value) != true)) {
                    this.AttachementsField = value;
                    this.RaisePropertyChanged("Attachements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailCC {
            get {
                return this.MailCCField;
            }
            set {
                if ((object.ReferenceEquals(this.MailCCField, value) != true)) {
                    this.MailCCField = value;
                    this.RaisePropertyChanged("MailCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailContent {
            get {
                return this.MailContentField;
            }
            set {
                if ((object.ReferenceEquals(this.MailContentField, value) != true)) {
                    this.MailContentField = value;
                    this.RaisePropertyChanged("MailContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailTO {
            get {
                return this.MailTOField;
            }
            set {
                if ((object.ReferenceEquals(this.MailTOField, value) != true)) {
                    this.MailTOField = value;
                    this.RaisePropertyChanged("MailTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((this.SendDateField.Equals(value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlertParams", Namespace="http://schemas.datacontract.org/2004/07/PrestigeMailService.WebService")]
    [System.SerializableAttribute()]
    public partial class AlertParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> EndGapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> GapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> IntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RefAlertField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> EndGap {
            get {
                return this.EndGapField;
            }
            set {
                if ((this.EndGapField.Equals(value) != true)) {
                    this.EndGapField = value;
                    this.RaisePropertyChanged("EndGap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> Gap {
            get {
                return this.GapField;
            }
            set {
                if ((this.GapField.Equals(value) != true)) {
                    this.GapField = value;
                    this.RaisePropertyChanged("Gap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> Interval {
            get {
                return this.IntervalField;
            }
            set {
                if ((this.IntervalField.Equals(value) != true)) {
                    this.IntervalField = value;
                    this.RaisePropertyChanged("Interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RefAlert {
            get {
                return this.RefAlertField;
            }
            set {
                if ((this.RefAlertField.Equals(value) != true)) {
                    this.RefAlertField = value;
                    this.RaisePropertyChanged("RefAlert");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WsItem", Namespace="http://schemas.datacontract.org/2004/07/PrestigeMailService.WebService")]
    [System.SerializableAttribute()]
    public partial class WsItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_Mail.IMail")]
    public interface IMail {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/RegisterAlert", ReplyAction="http://tempuri.org/IMail/RegisterAlertResponse")]
        void RegisterAlert(Helpers.ServiceReference_Mail.MailParams param, Helpers.ServiceReference_Mail.AlertParams alertParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/RegisterAlert", ReplyAction="http://tempuri.org/IMail/RegisterAlertResponse")]
        System.Threading.Tasks.Task RegisterAlertAsync(Helpers.ServiceReference_Mail.MailParams param, Helpers.ServiceReference_Mail.AlertParams alertParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/DeleteAlert", ReplyAction="http://tempuri.org/IMail/DeleteAlertResponse")]
        void DeleteAlert(System.Guid idAlert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/DeleteAlert", ReplyAction="http://tempuri.org/IMail/DeleteAlertResponse")]
        System.Threading.Tasks.Task DeleteAlertAsync(System.Guid idAlert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/DeleteAlerRange", ReplyAction="http://tempuri.org/IMail/DeleteAlerRangeResponse")]
        void DeleteAlerRange(System.Guid[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/DeleteAlerRange", ReplyAction="http://tempuri.org/IMail/DeleteAlerRangeResponse")]
        System.Threading.Tasks.Task DeleteAlerRangeAsync(System.Guid[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/SendByIdTemplate", ReplyAction="http://tempuri.org/IMail/SendByIdTemplateResponse")]
        void SendByIdTemplate(Helpers.ServiceReference_Mail.MailParams param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/SendByIdTemplate", ReplyAction="http://tempuri.org/IMail/SendByIdTemplateResponse")]
        System.Threading.Tasks.Task SendByIdTemplateAsync(Helpers.ServiceReference_Mail.MailParams param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/SendByTemplateName", ReplyAction="http://tempuri.org/IMail/SendByTemplateNameResponse")]
        void SendByTemplateName(Helpers.ServiceReference_Mail.MailParams param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/SendByTemplateName", ReplyAction="http://tempuri.org/IMail/SendByTemplateNameResponse")]
        System.Threading.Tasks.Task SendByTemplateNameAsync(Helpers.ServiceReference_Mail.MailParams param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/RegisterApplication", ReplyAction="http://tempuri.org/IMail/RegisterApplicationResponse")]
        void RegisterApplication(string nameApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/RegisterApplication", ReplyAction="http://tempuri.org/IMail/RegisterApplicationResponse")]
        System.Threading.Tasks.Task RegisterApplicationAsync(string nameApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/RegisterTemplate", ReplyAction="http://tempuri.org/IMail/RegisterTemplateResponse")]
        void RegisterTemplate(string templateName, int appId, string objet, System.Collections.Generic.Dictionary<string, string> parametres, string stringTemplate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/RegisterTemplate", ReplyAction="http://tempuri.org/IMail/RegisterTemplateResponse")]
        System.Threading.Tasks.Task RegisterTemplateAsync(string templateName, int appId, string objet, System.Collections.Generic.Dictionary<string, string> parametres, string stringTemplate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/TemplateList", ReplyAction="http://tempuri.org/IMail/TemplateListResponse")]
        Helpers.ServiceReference_Mail.WsItem[] TemplateList(int idApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/TemplateList", ReplyAction="http://tempuri.org/IMail/TemplateListResponse")]
        System.Threading.Tasks.Task<Helpers.ServiceReference_Mail.WsItem[]> TemplateListAsync(int idApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/ApplicationList", ReplyAction="http://tempuri.org/IMail/ApplicationListResponse")]
        Helpers.ServiceReference_Mail.WsItem[] ApplicationList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/ApplicationList", ReplyAction="http://tempuri.org/IMail/ApplicationListResponse")]
        System.Threading.Tasks.Task<Helpers.ServiceReference_Mail.WsItem[]> ApplicationListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/ParametersList", ReplyAction="http://tempuri.org/IMail/ParametersListResponse")]
        Helpers.ServiceReference_Mail.WsItem[] ParametersList(int idTemplate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMail/ParametersList", ReplyAction="http://tempuri.org/IMail/ParametersListResponse")]
        System.Threading.Tasks.Task<Helpers.ServiceReference_Mail.WsItem[]> ParametersListAsync(int idTemplate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMailChannel : Helpers.ServiceReference_Mail.IMail, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailClient : System.ServiceModel.ClientBase<Helpers.ServiceReference_Mail.IMail>, Helpers.ServiceReference_Mail.IMail {
        
        public MailClient() {
        }
        
        public MailClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegisterAlert(Helpers.ServiceReference_Mail.MailParams param, Helpers.ServiceReference_Mail.AlertParams alertParams) {
            base.Channel.RegisterAlert(param, alertParams);
        }
        
        public System.Threading.Tasks.Task RegisterAlertAsync(Helpers.ServiceReference_Mail.MailParams param, Helpers.ServiceReference_Mail.AlertParams alertParams) {
            return base.Channel.RegisterAlertAsync(param, alertParams);
        }
        
        public void DeleteAlert(System.Guid idAlert) {
            base.Channel.DeleteAlert(idAlert);
        }
        
        public System.Threading.Tasks.Task DeleteAlertAsync(System.Guid idAlert) {
            return base.Channel.DeleteAlertAsync(idAlert);
        }
        
        public void DeleteAlerRange(System.Guid[] ids) {
            base.Channel.DeleteAlerRange(ids);
        }
        
        public System.Threading.Tasks.Task DeleteAlerRangeAsync(System.Guid[] ids) {
            return base.Channel.DeleteAlerRangeAsync(ids);
        }
        
        public void SendByIdTemplate(Helpers.ServiceReference_Mail.MailParams param) {
            base.Channel.SendByIdTemplate(param);
        }
        
        public System.Threading.Tasks.Task SendByIdTemplateAsync(Helpers.ServiceReference_Mail.MailParams param) {
            return base.Channel.SendByIdTemplateAsync(param);
        }
        
        public void SendByTemplateName(Helpers.ServiceReference_Mail.MailParams param) {
            base.Channel.SendByTemplateName(param);
        }
        
        public System.Threading.Tasks.Task SendByTemplateNameAsync(Helpers.ServiceReference_Mail.MailParams param) {
            return base.Channel.SendByTemplateNameAsync(param);
        }
        
        public void RegisterApplication(string nameApp) {
            base.Channel.RegisterApplication(nameApp);
        }
        
        public System.Threading.Tasks.Task RegisterApplicationAsync(string nameApp) {
            return base.Channel.RegisterApplicationAsync(nameApp);
        }
        
        public void RegisterTemplate(string templateName, int appId, string objet, System.Collections.Generic.Dictionary<string, string> parametres, string stringTemplate) {
            base.Channel.RegisterTemplate(templateName, appId, objet, parametres, stringTemplate);
        }
        
        public System.Threading.Tasks.Task RegisterTemplateAsync(string templateName, int appId, string objet, System.Collections.Generic.Dictionary<string, string> parametres, string stringTemplate) {
            return base.Channel.RegisterTemplateAsync(templateName, appId, objet, parametres, stringTemplate);
        }
        
        public Helpers.ServiceReference_Mail.WsItem[] TemplateList(int idApplication) {
            return base.Channel.TemplateList(idApplication);
        }
        
        public System.Threading.Tasks.Task<Helpers.ServiceReference_Mail.WsItem[]> TemplateListAsync(int idApplication) {
            return base.Channel.TemplateListAsync(idApplication);
        }
        
        public Helpers.ServiceReference_Mail.WsItem[] ApplicationList() {
            return base.Channel.ApplicationList();
        }
        
        public System.Threading.Tasks.Task<Helpers.ServiceReference_Mail.WsItem[]> ApplicationListAsync() {
            return base.Channel.ApplicationListAsync();
        }
        
        public Helpers.ServiceReference_Mail.WsItem[] ParametersList(int idTemplate) {
            return base.Channel.ParametersList(idTemplate);
        }
        
        public System.Threading.Tasks.Task<Helpers.ServiceReference_Mail.WsItem[]> ParametersListAsync(int idTemplate) {
            return base.Channel.ParametersListAsync(idTemplate);
        }
    }
}
